language: php

php:
  - 7.2
  - 7.3

before_script:
  - cp .env.stub .env
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction
  - php artisan key:generate

script: phpunit

branches:
  only:
    - master
